version: '3'
volumes:
  dados:
services:
  db:
    image: postgres:9.6
    volumes:
      # data volume
      - dados:/var/lib/postgresql/data
      # scripts
      - .\scripts:/scripts
      - .\scripts\init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
  frontend:
    image: nginx:1.13
    volumes:
      # site
      - .\web:/usr/share/nginx/html/
      # reverse proxy nginx conf
      - .\nginx\default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  app:
    image: python:3.6
    volumes:
      # app
      - .\app:/app
    working_dir: /app
    command: ./app.sh
    # now with nginx reverse proxy there is no need to expose this port to external world
    #ports:
    #  - 8080:8080
